/**
 * Markdown export — single .md file with embedded base64 images.
 * Accepts AnalysedEntry[] (see core/schema.js); no app internals needed.
 *
 * @module export/markdown
 */

import { sourceDataUrl }                                          from '../render/canvas.js';
import { APP_NAME, SITE_URL, THRESHOLDS_FOOTER, DISCLAIMER_TEXT, CVD_TYPES } from './strings.js';

const CVD_DICHROMACIES = CVD_TYPES.filter((t) => t.key !== 'achromatopsia');

function anchor(filename) {
  return filename.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

function verdictLabel(verdict) {
  if (verdict === 'PASS') return '✓ PASS';
  if (verdict === 'FAIL') return '✗ FAIL';
  return '— NO TEXT';
}

function cvdRatio(contrast, pass) {
  return `${pass ? '✓' : '✗'} ${contrast.toFixed(2)}:1`;
}

/**
 * Build the full Markdown string for a batch of analysed entries.
 *
 * @param {import('../core/schema.js').AnalysedEntry[]} entries
 * @param {string} timestamp
 * @returns {string}
 */
export function buildMarkdown(entries, timestamp) {
  const lines = [];

  lines.push('# Image Colour Contrast Audit');
  lines.push('');
  lines.push(`_Generated ${timestamp}_`);
  lines.push(`_Generated by [${APP_NAME}](${SITE_URL})_`);
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push(`> **Automated analysis only.** ${DISCLAIMER_TEXT.replace('This report is generated automatically to help speed up accessibility review. ', '')}`);
  lines.push('');
  lines.push('---');
  lines.push('');

  // ── Summary ───────────────────────────────────────────────────────────────
  lines.push('## Summary');
  lines.push('');
  lines.push('| Image | Result |');
  lines.push('|-------|--------|');
  for (const e of entries) {
    lines.push(`| [${e.filename}](#${anchor(e.filename)}) | ${verdictLabel(e.report.verdict)} |`);
  }
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('## Accessibility Detail');
  lines.push('');

  // ── Per-image detail ──────────────────────────────────────────────────────
  entries.forEach((entry, idx) => {
    const { filename, report, previewDataUrl, pairAssets = [], cbSimAssets = [] } = entry;

    lines.push(`### ${idx + 1}. ${filename}`);
    lines.push('');
    lines.push(`- **Result:** ${verdictLabel(report.verdict)} — ${report.detail}`);
    lines.push('');

    if (previewDataUrl) {
      lines.push(`![${filename}](${previewDataUrl})`);
      lines.push('');
    }

    if (cbSimAssets.length) {
      lines.push('**Colour-blindness simulation:**');
      lines.push('');
      for (const a of cbSimAssets) {
        lines.push(`![${a.label} — ${a.note}](${a.dataUrl})`);
        lines.push('');
        lines.push(`_${a.label} — ${a.note}_`);
        lines.push('');
      }
    }

    if (report.hasText && report.colourPairs.length) {
      lines.push('**Colour combinations detected:**');
      lines.push('');
      // Background before Foreground
      lines.push('| Swatch | Background | Foreground | Ratio | AA | AAA | Check | Example words |');
      lines.push('|--------|-----------|-----------|-------|-----|-----|-------|---------------|');

      const assetByPair = new Map(pairAssets.map((a) => [a.pair, a]));

      for (const p of report.colourPairs) {
        const asset   = assetByPair.get(p);
        const swatch  = asset?.swatchDataUrl ? `![](${asset.swatchDataUrl})` : '';
        const webaim  = `[WebAIM ↗](https://webaim.org/resources/contrastchecker/?fcolor=${p.fgHex.slice(1)}&bcolor=${p.bgHex.slice(1)})`;
        const examples = p.examples.map((e) => `"${e}"`).join(', ');
        lines.push(`| ${swatch} | \`${p.bgHex}\` | \`${p.fgHex}\` | ${p.contrast.toFixed(2)}:1 | ${p.pass ? '✓ Pass' : '✗ Fail'} | ${p.passAaa ? '✓ Pass' : '✗ Fail'} | ${webaim} | ${examples} |`);
      }
      lines.push('');

      lines.push('**Contrast under colour-vision deficiency:**');
      lines.push('');
      const cvdHead = ['Background', 'Foreground', 'Normal', ...CVD_DICHROMACIES.map((t) => t.label)];
      lines.push(`| ${cvdHead.join(' | ')} |`);
      lines.push(`|${cvdHead.map(() => '---').join('|')}|`);
      for (const p of report.colourPairs) {
        const cells = [
          `\`${p.bgHex}\``,
          `\`${p.fgHex}\``,
          cvdRatio(p.contrast, p.pass),
          ...CVD_DICHROMACIES.map((t) => cvdRatio(p.cvd[t.key].contrast, p.cvd[t.key].pass))
        ];
        lines.push(`| ${cells.join(' | ')} |`);
      }
      lines.push('');

      const failing = report.colourPairs.filter((p) => !p.pass);
      if (failing.length) {
        lines.push('**Failing regions:**');
        lines.push('');
        for (const p of failing) {
          const asset = assetByPair.get(p);
          lines.push(`Background \`${p.bgHex}\` / Foreground \`${p.fgHex}\` — ${p.contrast.toFixed(2)}:1`);
          lines.push('');
          if (asset?.clipDataUrl) {
            lines.push(`![Failing region](${asset.clipDataUrl})`);
            lines.push('');
          }
        }
      }
    }

    lines.push('');
  });

  // ── Footer ────────────────────────────────────────────────────────────────
  lines.push('---');
  lines.push('');
  lines.push(`> ${THRESHOLDS_FOOTER}`);
  lines.push(`> Generated by [${APP_NAME}](${SITE_URL})`);
  lines.push('');

  return lines.join('\n');
}

/**
 * Trigger a browser download of the Markdown report.
 *
 * @param {string} markdown
 * @param {string} filename
 */
export function downloadMarkdown(markdown, filename) {
  const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8' });
  const url  = URL.createObjectURL(blob);
  const a    = Object.assign(document.createElement('a'), { href: url, download: filename });
  document.body.append(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
