/**
 * Markdown export — single .md file with embedded base64 images.
 * Accepts AnalysedEntry[] (see core/schema.js); no app internals needed.
 *
 * @module export/markdown
 */

import {
  APP_NAME, SITE_URL, THRESHOLDS_FOOTER, DISCLAIMER_TEXT, checkInfoUrl,
  VESTIBULAR_CHECKER_URL, VESTIBULAR_CHECKER_FULL_LABEL
} from './strings.js';
import { pairChecks, wcagLine, advancedLine, pairBadges, statusWord, CHECK_GROUPS } from './checks.js';

function anchor(filename) {
  return filename.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

function verdictLabel(verdict) {
  if (verdict === 'PASS') return '✓ PASS';
  if (verdict === 'FAIL') return '✗ FAIL';
  return '— NO TEXT';
}

/**
 * Build the full Markdown string for a batch of analysed entries.
 *
 * @param {import('../core/schema.js').AnalysedEntry[]} entries
 * @param {string} timestamp
 * @returns {string}
 */
export function buildMarkdown(entries, timestamp) {
  const lines = [];

  lines.push('# Image Colour Contrast Audit');
  lines.push('');
  lines.push(`_Generated ${timestamp}_`);
  lines.push(`_Generated by [${APP_NAME}](${SITE_URL})_`);
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push(`> **Automated analysis only.** ${DISCLAIMER_TEXT.replace('This report is generated automatically to help speed up accessibility review. ', '')}`);
  lines.push('');
  lines.push('---');
  lines.push('');

  // ── Summary ───────────────────────────────────────────────────────────────
  lines.push('## Summary');
  lines.push('');
  lines.push('| Image | Result |');
  lines.push('|-------|--------|');
  for (const e of entries) {
    lines.push(`| [${e.filename}](#${anchor(e.filename)}) | ${verdictLabel(e.report.verdict)} |`);
  }
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('## Accessibility Detail');
  lines.push('');

  // ── Per-image detail ──────────────────────────────────────────────────────
  entries.forEach((entry, idx) => {
    const { filename, report, previewDataUrl, pairAssets = [], cbSimAssets = [] } = entry;

    lines.push(`### ${idx + 1}. ${filename}`);
    lines.push('');
    lines.push(`- **Result:** ${verdictLabel(report.verdict)} — ${report.detail}`);
    lines.push('');

    if (previewDataUrl) {
      lines.push(`![${filename}](${previewDataUrl})`);
      lines.push('');
    }

    if (cbSimAssets.length) {
      lines.push('**Colour-blindness simulation:**');
      lines.push('');
      for (const a of cbSimAssets) {
        lines.push(`![${a.label} — ${a.note}](${a.dataUrl})`);
        lines.push('');
        lines.push(`_${a.label} — ${a.note}_`);
        lines.push('');
      }
    }

    if (report.hasText && report.colourPairs.length) {
      lines.push('**Contrast results:**');
      lines.push('');
      lines.push(`_${wcagLine(report)}_`);
      lines.push(`_${advancedLine(report)}_`);
      lines.push('');
      lines.push(`For single-pair vestibular checking, visit [${VESTIBULAR_CHECKER_FULL_LABEL}](${VESTIBULAR_CHECKER_URL}).`);
      lines.push('');

      const assetByPair = new Map(pairAssets.map((a) => [a.pair, a]));
      for (const p of report.colourPairs) {
        const asset  = assetByPair.get(p);
        const words  = p.examples.map((e) => `"${e}"`).join(', ');
        const webaim = `https://webaim.org/resources/contrastchecker/?fcolor=${p.fgHex.slice(1)}&bcolor=${p.bgHex.slice(1)}`;
        const badges = pairBadges(p).map((b) => `${b.short} ${statusWord(b.status)}`).join(' · ');

        lines.push('<details>');
        lines.push(`<summary><strong>${badges}</strong> — \`${p.bgHex}\` background / \`${p.fgHex}\` foreground${words ? ` — ${words}` : ''}</summary>`);
        lines.push('');
        if (asset?.swatchDataUrl) {
          lines.push(`![Background / foreground swatch](${asset.swatchDataUrl})`);
          lines.push('');
        }
        lines.push(`[Check this pair on WebAIM ↗](${webaim})`);
        lines.push('');
        lines.push('| Check | Value | Status | What it means |');
        lines.push('|-------|-------|--------|---------------|');
        const checks = pairChecks(p);
        for (const grp of CHECK_GROUPS) {
          lines.push(`| **${grp.label}** | | | |`);
          for (const c of checks.filter((check) => check.group === grp.id)) {
            lines.push(`| [${c.label}](${checkInfoUrl(c.id)}) | ${c.value || '—'} | ${c.status} | ${c.detail} |`);
          }
        }
        lines.push('');
        if (asset?.clipDataUrl) {
          lines.push('Where this combination appears in the image:');
          lines.push('');
          lines.push(`![Cropped image region](${asset.clipDataUrl})`);
          lines.push('');
        }
        lines.push('</details>');
        lines.push('');
      }
    }

    lines.push('');
  });

  // ── Footer ────────────────────────────────────────────────────────────────
  lines.push('---');
  lines.push('');
  lines.push(`> ${THRESHOLDS_FOOTER}`);
  lines.push(`> Generated by [${APP_NAME}](${SITE_URL})`);
  lines.push('');

  return lines.join('\n');
}

/**
 * Trigger a browser download of the Markdown report.
 *
 * @param {string} markdown
 * @param {string} filename
 */
export function downloadMarkdown(markdown, filename) {
  const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8' });
  const url  = URL.createObjectURL(blob);
  const a    = Object.assign(document.createElement('a'), { href: url, download: filename });
  document.body.append(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
