/**
 * PDF export via PDFKit — ISO 14289-1 (PDF/UA-1) compliant.
 *
 * Replaces the pdfmake implementation. Uses the `src/lib/pdf-ua/` wrapper
 * which handles PDFKit 0.18.0 bug workarounds (see ADR 010 and the wrapper's
 * module-level comment for details).
 *
 * Public API is unchanged:
 *   downloadPdf(entries, timestamp, filename) — browser download
 *
 * Additional export for tests:
 *   buildPdf(entries, timestamp) — returns Promise<Buffer>
 *
 * @module export/pdf
 */

import { fileURLToPath } from 'node:url';
import { join }          from 'node:path';

import {
  createDocument,
  addHeading,
  addParagraph,
  addFigure,
  artifact,
  toBlob,
  toBuffer,
} from '../lib/pdf-ua/index.js';

import {
  APP_NAME,
  THRESHOLDS_FOOTER,
  DISCLAIMER_TEXT,
} from './strings.js';

import {
  pairChecks,
  wcagLine,
  advancedLine,
  pairBadges,
  statusWord,
  CHECK_GROUPS,
} from './checks.js';

// ── Font paths ───────────────────────────────────────────────────────────────
// Roboto TTF files bundled with pdfmake. The wrapper never uses AFM built-ins.
const __dirname = fileURLToPath(new URL('.', import.meta.url));
const FONT_DIR  = join(__dirname, '../../node_modules/pdfmake/fonts/Roboto');
const FONTS     = {
  regular: join(FONT_DIR, 'Roboto-Regular.ttf'),
  medium:  join(FONT_DIR, 'Roboto-Medium.ttf'),
};

// Available page width for A4 with 40 pt left/right margins (595.28 – 80 ≈ 515).
const PAGE_W = 515;

// ── Helpers ──────────────────────────────────────────────────────────────────

/** Map a check/verdict status to a semantic key. */
function statusStyle(status) {
  if (status === 'PASS' || status === 'SAFE') return 'pass';
  if (status === 'FAIL' || status === 'HIGH') return 'fail';
  return 'warn';
}

/**
 * Build a `doc.table()` cell object styled as a status pill.
 * The background colour is rendered by PDFKit's table engine and is marked
 * as an Artifact internally; the text carries the semantic status value.
 */
function pillCell(status) {
  const colours = {
    pass:    { backgroundColor: '#dcfce7', color: '#14532d' },
    fail:    { backgroundColor: '#fee2e2', color: '#7f1d1d' },
    warn:    { backgroundColor: '#fef3c7', color: '#663a00' },
    neutral: { backgroundColor: '#f0f2f5', color: '#4b5563' },
  };
  const c = colours[statusStyle(status)] || colours.neutral;
  return {
    text: status,
    ...c,
    font: { size: 8 },
    padding: [6, 2, 6, 2],
  };
}

// ── Document builder ─────────────────────────────────────────────────────────

/**
 * Build the full audit-report PDFDocument.
 *
 * @param {import('../core/schema.js').AnalysedEntry[]} entries
 * @param {string} timestamp
 * @returns {import('pdfkit')} A PDFDocument ready to be finalised.
 */
function buildDocument(entries, timestamp) {
  const doc = createDocument({
    title:   'Audit Report',
    fonts:   FONTS,
    lang:    'en',
    size:    'A4',
    margins: { top: 50, bottom: 50, left: 40, right: 40 },
  });

  // ── Branded header ────────────────────────────────────────────────────────
  // Navy background is a page-level Artifact (decorative fill, not content).
  // The heading text is a single H1 structure element whose readable text is
  // "Image Colour Contrast Checker"; the white/orange colour split is visual.
  const headerTop = doc.y;
  artifact(doc, (d) => {
    d.rect(doc.page.margins.left, headerTop, PAGE_W, 70).fill('#061528');
  });

  const h1 = doc.struct('H1');
  doc.addStructure(h1);
  h1.add(doc.markStructureContent('H1', () => {
    doc.font('Medium').fontSize(18)
       .fillColor('#ffffff').text('Image Colour ', { continued: true })
       .fillColor('#FF7C00').text('Contrast Checker', { continued: false });
  }));
  h1.end();

  addParagraph(doc,
    'Drop in images for WCAG 2.2 AA / AAA compliance and advanced perceptual checks. '
    + 'Runs entirely in your browser — nothing is uploaded.',
    { fontSize: 8.75, fillColor: '#63D2FF' }
  );
  doc.moveDown(0.5);

  // ── Report title + timestamp ──────────────────────────────────────────────
  doc.fillColor('#000000');
  addHeading(doc, 2, 'Audit Report',          { font: 'Medium', fontSize: 14 });
  addParagraph(doc, `Generated ${timestamp}`, { fontSize: 9, fillColor: '#4b5563' });
  addParagraph(doc, `Generated by ${APP_NAME}`,{ fontSize: 9, fillColor: '#4b5563' });
  doc.moveDown(0.5);

  // ── Disclaimer ────────────────────────────────────────────────────────────
  const disclTop = doc.y;
  artifact(doc, (d) => {
    d.rect(doc.page.margins.left, disclTop, PAGE_W, 40).fill('#fef3c7');
  });
  const shortDisclaimer = DISCLAIMER_TEXT.replace(
    'This report is generated automatically to help speed up accessibility review. ', ''
  );
  addParagraph(doc, `Automated analysis only — ${shortDisclaimer}`, {
    fontSize: 9, fillColor: '#1a1a1a',
  });
  doc.moveDown(0.75);

  // ── Summary table ─────────────────────────────────────────────────────────
  doc.fillColor('#000000');
  addHeading(doc, 2, 'Summary', { font: 'Medium', fontSize: 14 });
  doc.table({
    columnStyles: [{ width: 380 }, { width: 100 }],
    defaultStyle: { fontSize: 10 },
    data: [
      [
        { type: 'TH', scope: 'column', text: 'Image',  font: { src: FONTS.medium }, backgroundColor: '#f3f4f6' },
        { type: 'TH', scope: 'column', text: 'Result', font: { src: FONTS.medium }, backgroundColor: '#f3f4f6' },
      ],
      ...entries.map((e) => {
        const vs = e.report.flag ? 'FAIL' : (e.report.verdict === 'PASS' ? 'PASS' : 'NO TEXT');
        return [{ text: e.filename }, pillCell(vs)];
      }),
    ],
  });
  doc.moveDown();

  // ── Per-image sections ────────────────────────────────────────────────────
  entries.forEach((entry, idx) => {
    if (idx > 0) doc.addPage();
    doc.fillColor('#000000');

    // 1.5 Heading + preview
    addHeading(doc, 2, entry.filename, { font: 'Medium', fontSize: 14 });
    if (entry.previewDataUrl) {
      addFigure(doc, entry.previewDataUrl, `Preview of ${entry.filename}`, { width: 420 });
    }

    // 1.6 Result line
    const vs = entry.report.flag
      ? 'FAIL'
      : (entry.report.verdict === 'PASS' ? 'PASS' : 'NO TEXT');
    addParagraph(doc, `Result: ${vs} — ${entry.report.detail}`, { fontSize: 10 });

    // 1.7 CVD simulation images
    if (entry.cbSimAssets && entry.cbSimAssets.length) {
      addHeading(doc, 3, 'Colour-blindness simulation', { font: 'Medium', fontSize: 12 });
      for (const asset of entry.cbSimAssets) {
        addFigure(doc, asset.dataUrl,
          `${asset.label} colour vision simulation — ${asset.note}`,
          { width: 220 }
        );
        addParagraph(doc, `${asset.label} — ${asset.note}`, {
          fontSize: 8, fillColor: '#4b5563', oblique: true,
        });
      }
      doc.moveDown(0.5);
    }

    // 1.8 Contrast results + 1.9 per-pair blocks
    if (entry.report.hasText && entry.report.colourPairs && entry.report.colourPairs.length) {
      doc.fillColor('#000000');
      addHeading(doc, 3, 'Contrast results', { font: 'Medium', fontSize: 12 });
      addParagraph(doc, wcagLine(entry.report),    { fontSize: 10, fillColor: '#374151', oblique: true });
      addParagraph(doc, advancedLine(entry.report), { fontSize: 10, fillColor: '#374151', oblique: true });

      const assetMap = new Map((entry.pairAssets || []).map((a) => [a.pair, a]));

      for (const pair of entry.report.colourPairs) {
        const asset = assetMap.get(pair);
        doc.moveDown(0.5);
        doc.fillColor('#000000');

        // 1.9.1 Swatch (decorative) + badge strip + hex pair label
        if (asset?.swatchDataUrl) {
          // Swatch is a decorative colour chip — Artifact, not Figure.
          const swatchY = doc.y;
          artifact(doc, (d) => {
            d.image(asset.swatchDataUrl, doc.page.margins.left, swatchY, { width: 48, height: 14 });
          });
          doc.y = swatchY + 18;
        }
        const badges = pairBadges(pair)
          .map((b) => `${b.short} ${statusWord(b.status)}`)
          .join('    ');
        addParagraph(doc,
          `${badges}    Background ${pair.bgHex}  ·  Foreground ${pair.fgHex}`,
          { font: 'Regular', fontSize: 10, fillColor: '#000000' }
        );

        // 1.9.2 Examples + links (plain text v1 — tagged Link elements are Phase 2)
        const exStr = pair.examples && pair.examples.length
          ? pair.examples.map((e) => `"${e}"`).join(', ') + '   '
          : '';
        addParagraph(doc, `${exStr}WebAIM   Vestibular Accessible Design Checker`, {
          fontSize: 9, fillColor: '#374151',
        });

        // 1.9.3 Checks table
        const checks    = pairChecks(pair);
        const tableRows = [[
          { type: 'TH', scope: 'column', text: 'Check',         font: { src: FONTS.medium }, backgroundColor: '#f3f4f6' },
          { type: 'TH', scope: 'column', text: 'Value',         font: { src: FONTS.medium }, backgroundColor: '#f3f4f6' },
          { type: 'TH', scope: 'column', text: 'Status',        font: { src: FONTS.medium }, backgroundColor: '#f3f4f6' },
          { type: 'TH', scope: 'column', text: 'What it means', font: { src: FONTS.medium }, backgroundColor: '#f3f4f6' },
        ]];

        for (const grp of CHECK_GROUPS) {
          // Group separator: TH spanning the row, bold, grey background.
          // Four cells are used instead of colSpan since PDFKit's table API
          // does not guarantee colSpan support.
          tableRows.push([
            { type: 'TH', scope: 'row', text: grp.label,
              font: { src: FONTS.medium, size: 8 },
              backgroundColor: '#e5e7eb', color: '#1a1a1a' },
            { text: '' },
            { text: '' },
            { text: '' },
          ]);
          for (const c of checks.filter((ch) => ch.group === grp.id)) {
            tableRows.push([
              { text: c.label },
              { text: c.value || '—' },
              pillCell(c.status),
              { text: c.detail, oblique: true },
            ]);
          }
        }

        doc.table({
          data: tableRows,
          columnStyles: [
            { width: 110 },
            { width: 80  },
            { width: 80  },
            { width: 225 },
          ],
        });

        // 1.9.4 Clip image (conditional)
        if (asset?.clipDataUrl) {
          addParagraph(doc, 'Where this combination appears:', {
            fontSize: 9, fillColor: '#374151', oblique: true,
          });
          addFigure(doc, asset.clipDataUrl,
            `Cropped region showing where ${pair.bgHex} background with `
            + `${pair.fgHex} foreground text appears in the image`,
            { width: 360 }
          );
        }
      }
    }
  });

  // ── Footer ────────────────────────────────────────────────────────────────
  doc.moveDown();
  doc.fillColor('#000000');
  addParagraph(doc, THRESHOLDS_FOOTER, { fontSize: 9, fillColor: '#4b5563', oblique: true });
  addParagraph(doc, `Generated by ${APP_NAME}`, { fontSize: 9, fillColor: '#4b5563' });

  return doc;
}

// ── Public API ───────────────────────────────────────────────────────────────

/**
 * Generate and download the PDF report in the browser.
 *
 * @param {import('../core/schema.js').AnalysedEntry[]} entries
 * @param {string} timestamp
 * @param {string} filename
 */
export async function downloadPdf(entries, timestamp, filename) {
  const blob = await toBlob(buildDocument(entries, timestamp));
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href     = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

/**
 * Build the PDF and return it as a Buffer (Node.js / test path).
 * Does not touch the DOM.
 *
 * @param {import('../core/schema.js').AnalysedEntry[]} entries
 * @param {string} timestamp
 * @returns {Promise<Buffer>}
 */
export async function buildPdf(entries, timestamp) {
  return toBuffer(buildDocument(entries, timestamp));
}
